### ISSUE TITLE
Doesn't work in python 2.7

### ISSUE THREAD

**Issue by morganwu277** [vickysam/ComplexHTTPServer#2]
Which tells me need module of `socketserver`

**Comment by vickysam** [comment]
It has been ported to Python 3

**Comment by vickysam** [comment]
morganwu277 - you can submit a pull request to make it compatible with both Python 2 and 3

**Comment by vickysam** [comment]
Marking this Resolved :  7279efe564b2229e6383336c7df943c7b1a381c4
